import type { Location } from '@/lib/types';
import type { GeocodeResult } from '@/lib/maps/geocoding';

/**
 * Defines the structure for a request to get a single hint from the AI service.
 */
export interface SingleHintRequest {
  /** The geographical location for which a hint is requested. */
  location: Location;
  /** The current round number in the game. */
  roundNumber: number;
  /** The current game mode (e.g., 'standard', 'time-attack'). */
  gameMode: string;
  /** The sequential number of the hint being requested for the current round. */
  hintNumber: number;
  /** An array of hints that have been previously provided for the same location. */
  previousHints?: string[];
  /** Geocoded information about the location, including country, region, etc. */
  countryInfo: GeocodeResult;
}

/**
 * Defines the structure for a single hint response from the AI service.
 */
export interface SingleHintResponse {
  /** The hint text generated by the AI. */
  hint: string;
  /** A score from 0 to 1 indicating the AI's confidence in the hint's accuracy and relevance. */
  confidence: number;
  /** The category of the hint, which helps in classifying the type of information provided. */
  category: 'geographical' | 'cultural' | 'architectural' | 'environmental' | 'general';
  /** The estimated difficulty of the hint. */
  difficulty: 'easy' | 'medium' | 'hard';
}

/**
 * Defines the structure for a response containing a text-based hint, such as revealing letters of the country name.
 */
export interface TextHintResponse {
  /** The formatted hint string (e.g., 'C A _ A D A'). */
  hint: string;
  /** The type of text hint provided. */
  type: 'country-letters';
  /** The cost of the hint, which may increase with each hint level. */
  cost: number;
  /** The current level of the hint, used to determine progression. */
  hintLevel: number;
  /** A boolean indicating whether the hint is fully revealed. */
  isComplete: boolean;
}

/**
 * Defines the essential context about a location, used for generating relevant hints.
 */
export interface LocationContext {
  /** The name of the country. */
  country: string;
  /** The ISO 3166-1 alpha-2 country code. */
  countryCode: string;
  /** A human-readable, formatted address string for the location. */
  formattedAddress: string;
}
